"""create employee_of_month

Revision ID: 2e4fb6503324
Revises: 4527f3b82ba0
Create Date: 2025-08-21 22:58:05.673893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4fb6503324'
down_revision = '4527f3b82ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_costs_department_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_costs_year_month'))

    op.drop_table('payroll_costs')
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaves_validated_by_id'))
        batch_op.drop_constraint(batch_op.f('fk_leaves_validated_by'), type_='foreignkey')
        batch_op.drop_column('notified_at')
        batch_op.drop_column('validated_at')
        batch_op.drop_column('validated_by_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validated_by_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('validated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('notified_at', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_leaves_validated_by'), 'users', ['validated_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_leaves_validated_by_id'), ['validated_by_id'], unique=False)

    op.create_table('payroll_costs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('department_id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.INTEGER(), nullable=False),
    sa.Column('base_salary', sa.NUMERIC(precision=14, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('overtime_cost', sa.NUMERIC(precision=14, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('leave_cost', sa.NUMERIC(precision=14, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('benefits_cost', sa.NUMERIC(precision=14, scale=2), server_default=sa.text("'0'"), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=8), server_default=sa.text("'XOF'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'year', 'month', name=op.f('uq_payroll_costs_dep_month'))
    )
    with op.batch_alter_table('payroll_costs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_costs_year_month'), ['year', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_costs_department_id'), ['department_id'], unique=False)

    # ### end Alembic commands ###
