"""overtime: new fields

Revision ID: 7e3b3ec7d351
Revises: 3936e4149efd
Create Date: 2025-09-12 22:10:48.225845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3b3ec7d351'
down_revision = '3936e4149efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('work_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'weekday', name='uq_schedule_user_day')
    )
    with op.batch_alter_table('work_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_schedules_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('overtimes', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.TEXT(),
               type_=sa.Enum('manual', 'auto', name='overtimesource'),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'"))
        batch_op.alter_column('auto_state',
               existing_type=sa.TEXT(),
               type_=sa.Enum('auto_approved', 'needs_review', name='autostate'),
               existing_nullable=True)
        batch_op.drop_index('uq_overtimes_user_date_source')
        batch_op.create_unique_constraint('uq_overtimes_user_date_source', ['user_id', 'work_date', 'source'])
        batch_op.create_index(batch_op.f('ix_overtimes_work_date'), ['work_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overtimes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_overtimes_work_date'))
        batch_op.drop_constraint('uq_overtimes_user_date_source', type_='unique')
        batch_op.create_index('uq_overtimes_user_date_source', ['user_id', 'work_date', 'source'], unique=False)
        batch_op.alter_column('auto_state',
               existing_type=sa.Enum('auto_approved', 'needs_review', name='autostate'),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.Enum('manual', 'auto', name='overtimesource'),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'manual'"))

    with op.batch_alter_table('work_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_schedules_user_id'))

    op.drop_table('work_schedules')
    op.drop_table('holidays')
    # ### end Alembic commands ###
