"""add employee_of_month table

Revision ID: edc55a98bc6b
Revises: 2e4fb6503324
Create Date: 2025-08-21 23:48:43.742714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edc55a98bc6b'
down_revision = '2e4fb6503324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_of_month',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period', name='uq_employee_of_month_period')
    )
    with op.batch_alter_table('employee_of_month', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_of_month_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_of_month_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_of_month', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_of_month_user_id'))
        batch_op.drop_index(batch_op.f('ix_employee_of_month_period'))

    op.drop_table('employee_of_month')
    # ### end Alembic commands ###
